/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_ntt_oss_heapstats_mbean_HeapStats */

#ifndef _Included_jp_co_ntt_oss_heapstats_mbean_HeapStats
#define _Included_jp_co_ntt_oss_heapstats_mbean_HeapStats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_co_ntt_oss_heapstats_mbean_HeapStats
 * Method:    registerNatives
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_co_ntt_oss_heapstats_mbean_HeapStats_registerNatives
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
